# 服务端口
server:
  port: 9090
  servlet:
    # 接口前缀
    context-path: /${school.name}
    encoding:
      force: false
      charset: UTF-8

# mysql数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?serverTimezone=GMT%2B8
    username: root
    password: Zl123456!
  redis:
    host: 127.0.0.1
    port: 6379

school:
    name: @project.name@
    websit: @project.groupId@
