#激活生产环境 
spring:
  profiles:
    active: dev

#mybatis-plus:
#   mapper-locations: classpath*:/mapper/*.xml
#   type-aliases-package: com.example
#      global-config:
#        banner: false
#        db-config:
#          id-type: input